# Generated by Django 4.2.5 on 2023-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to='', verbose_name='photo de profil'),
        ),
    ]
