# Generated by Django 4.2.5 on 2023-10-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
