# Generated by Django 4.2.5 on 2023-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to='', verbose_name='photo de profile'),
        ),
    ]
