# Generated by Django 4.2.5 on 2023-10-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guest_access_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Guest Access Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guest_access_code_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guest Access Code Set At'),
        ),
    ]
