# Generated by Django 4.2.5 on 2023-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_guest_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
