# Generated by Django 4.2.5 on 2023-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('date_started', models.DateField(auto_now=True, verbose_name='date started')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('tasks', models.TextField(blank=True, max_length=255, null=True, verbose_name='tasks')),
                ('link_git', models.URLField(blank=True, null=True, verbose_name='link git')),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Presentation file')),
            ],
        ),
    ]
