# Generated by Django 4.2.5 on 2023-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_remove_softskill_cvs_remove_softskill_projects_and_more'),
        ('project', '0004_project_softskills_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='softskills',
            field=models.ManyToManyField(blank=True, to='skill.softskill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='skill.technology'),
        ),
    ]
