# Generated by Django 4.2.5 on 2023-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Documents'),
        ),
    ]
