# Generated by Django 4.2.5 on 2023-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='tasks'),
        ),
    ]
