# Generated by Django 4.2.5 on 2023-11-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('welcome_sentence', models.CharField(default='Bienvenue !', max_length=100)),
                ('introduction_text', models.TextField(blank=True, max_length=600, null=True)),
                ('is_visible', models.BooleanField(blank=True, default=False, null=True, verbose_name='is visible')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
