# Generated by Django 4.2.5 on 2023-10-05 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_language_user_softskill_user_technology_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
        migrations.AddField(
            model_name='technology',
            name='level',
            field=models.PositiveIntegerField(default=0, max_length=1024, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Level'),
        ),
    ]
