# Generated by Django 4.2.5 on 2023-10-06 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_remove_technology_description_technology_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='description',
        ),
        migrations.AddField(
            model_name='softskill',
            name='level',
            field=models.PositiveIntegerField(default=0, max_length=1024, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Level'),
        ),
    ]
