# Generated by Django 4.2.5 on 2023-10-06 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_remove_softskill_description_softskill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskill',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Level'),
        ),
    ]
