# Generated by Django 4.2.5 on 2023-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_alter_language_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='cvs',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cvs',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='projects',
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2, verbose_name='level'),
        ),
    ]
