# Generated by Django 4.2.5 on 2023-10-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_remove_softskill_cvs_remove_softskill_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='cvs',
        ),
    ]
