# Generated by Django 4.2.5 on 2023-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_remove_softskill_cvs_remove_softskill_projects_and_more'),
        ('cv', '0002_cv_user_experience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='cvs',
        ),
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='cv.experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='profil',
            field=models.TextField(default='entrez une descirption de votre profil', max_length=255, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='cv',
            name='softskills',
            field=models.ManyToManyField(blank=True, to='skill.softskill'),
        ),
    ]
