# Generated by Django 4.2.5 on 2023-10-10 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_remove_language_cvs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0003_remove_experience_cvs_cv_experiences_cv_profil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(default='entrez une descirption', max_length=255, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.ManyToManyField(blank=True, to='skill.language'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profil',
            field=models.TextField(default='entrez une descirption de votre profil', max_length=255, verbose_name='profil'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('school_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('location', models.CharField(max_length=100, verbose_name='company location')),
                ('date_started', models.DateField(verbose_name='date started')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('rncp_level', models.CharField(blank=True, choices=[('CAP', '3'), ('BAC', '4'), ('BAC+2', '5'), ('LICENCE', '6'), ('MASTER|MBA|Executive MAB', '7'), ('DOCTORAT|DBA|PhD', '8')], default='4', max_length=24, verbose_name='RNCP Level')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='formations',
            field=models.ManyToManyField(blank=True, to='cv.formation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='cv.hobbies'),
        ),
    ]
