# Generated by Django 4.2.5 on 2023-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_remove_language_cvs'),
        ('cv', '0004_hobbies_cv_languages_alter_cv_profil_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='skill.technology'),
        ),
    ]
