# Generated by Django 4.2.5 on 2023-10-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_cv_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='background_education_title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='background_experience_title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='background_personal_details_panel',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='background_title_panel',
        ),
    ]
