# Generated by Django 4.2.5 on 2023-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_remove_cv_background_education_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='certificate_picture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Certificate picture'),
        ),
    ]
