# Generated by Django 4.2.5 on 2023-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_cv_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='certificate_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certificate picture'),
        ),
    ]
