# Generated by Django 4.2.5 on 2023-10-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_hobbies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='profil',
            field=models.TextField(default='entrez une description de votre profil', max_length=300, verbose_name='profil'),
        ),
    ]
