# Generated by Django 4.2.5 on 2023-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_cv_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='rncp_level',
            field=models.CharField(blank=True, choices=[('CAP', '3'), ('BAC', '4'), ('BAC+2', '5'), ('LICENCE Niv.6', '6'), ('MASTER|MBA|Executive MAB Niv.7', '7'), ('DOCTORAT|DBA|PhD Niv.8', '8')], default='4', max_length=30, verbose_name='RNCP Level'),
        ),
    ]
