# Generated by Django 4.2.5 on 2023-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_cv_can_be_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='profil',
            field=models.TextField(default='entrez une description de votre profil', max_length=600, verbose_name='profil'),
        ),
    ]
