# Generated by Django 4.2.5 on 2023-12-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_alter_cv_can_be_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('date_started',)},
        ),
    ]
