# Generated by Django 4.2.5 on 2024-01-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-date_started',)},
        ),
    ]
